### ISSUE TITLE
Document where this library is used

### ISSUE THREAD

**Issue by rugk** [nrdcg/desec#10]
IMHO it's a good practice for a small library like this to have a wiki page or something, where people can write when they use the library.

It adds some popularity to it and shows you that your library is used/for what it is used.

## Examples

* ~~https://github.com/libdns/libdns/issues/43 / https://github.com/libdns/libdns/issues/43 has [libdns support](https://github.com/libdns/desec) and/for [usage in the webserver Caddy](https://github.com/caddy-dns/desec).~~ **edit:** or wait [it does not actually use it](https://github.com/libdns/desec/blob/main/provider.go)?

## Alternatives

[Sure you may also use GitHub features for this like the page here](https://github.com/nrdcg/desec/network/dependents), but there you don't see for what it is used and it may not highlight the big projects. So a custom list with some explanation would be nice IMHO.

**Comment by ldez** [comment]
Hello,

I don't share your opinion about a Wiki page, I think the "used by" feature of GitHub is enough, I don't want to be a "famous" library.
For me, the only place where this client can be referenced is on the deSec website.

Yes, Caddy (libDNS) doesn't use "external clients" for API. They prefer to recreate an internal client to have "no dependency". I don't share this approach, for me, it's better to put the effort in one place and dependencies are not a problem, but :shrug:.

FYI, I created this client for [lego](https://github.com/go-acme/lego) which is used by [Traefik](https://github.com/traefik/traefik).
